name: netaccess
version: 0.1.0-experimental
summary: Approve/revoke your machine's internet access at IIT Madras
description: |
    netacess is a command line application which allows you to login to IIT
    Madras' netacess website and approve/revoke the inernet access of your
    machine.

confinement: devmode

parts:
    netacess:
        plugin: rust
        source: .

apps:
    netaccess:
        command: netaccess
