name: netaccess
version: 0.2.0
summary: Approve/revoke your machine's internet access at IIT Madras
description: |
    netacess is a command line application which allows you to login to IIT
    Madras' netacess website and approve/revoke the inernet access of your
    machine.

grade: stable
confinement: strict

parts:
    netacess:
        plugin: rust
        source: .
        build-packages:
            - pkg-config
            - libssl-dev

apps:
    netaccess:
        command: netaccess
        plugs:
            - network
